#!/usr/bin/env node

/**
 * Build-time configuration generator for Fellow n8n nodes
 *
 * Generates apiConfig.ts with environment-specific API base URL patterns.
 * This allows us to create separate builds for production and staging
 * without using runtime environment variables (which n8n doesn't allow).
 *
 * Usage:
 *   node scripts/generateConfig.js prod
 *   node scripts/generateConfig.js staging
 */

const fs = require('fs');
const path = require('path');

const environment = process.argv[2] || 'dev';

// Define API URL patterns for each environment
const configs = {
  prod: {
    baseUrlPattern: 'https://{subdomain}.fellow.app/api/v1',
    skipSslValidation: false,
    description: 'Production environment',
  },
  staging: {
    baseUrlPattern: 'https://{subdomain}.staging.fellow.co/api/v1',
    skipSslValidation: false,
    description: 'Staging environment',
  },
  dev: {
    baseUrlPattern: 'https://{subdomain}.fellow.dev/api/v1',
    skipSslValidation: true,
    description: 'Development environment',
  },
};

const config = configs[environment];

if (!config) {
  console.error(`Error: Unknown environment "${environment}"`);
  console.error(`Available environments: ${Object.keys(configs).join(', ')}`);
  process.exit(1);
}

// Generate TypeScript configuration file
const content = `/**
 * Auto-generated API configuration
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: scripts/generateConfig.js
 * Environment: ${environment}
 * Description: ${config.description}
 * Generated at: ${new Date().toISOString()}
 */

export const FELLOW_API_BASE_URL_PATTERN = '${config.baseUrlPattern}';
export const FELLOW_SKIP_SSL_VALIDATION = ${config.skipSslValidation};
export const FELLOW_ENVIRONMENT: 'dev' | 'staging' | 'prod' = '${environment}';
`;

const outputPath = path.join(__dirname, '../nodes/Fellow/apiConfig.ts');

try {
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`✓ Generated ${outputPath} for ${environment} environment`);
  console.log(`  Base URL pattern: ${config.baseUrlPattern}`);
} catch (error) {
  console.error(`Error writing config file:`, error);
  process.exit(1);
}
